name: Java CI

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: 'gradle'
        cache-dependency-path: | # optional
          **/*.gradle*
          **/gradle-wrapper.properties
    - name: Grand execute permission for gradlew
      run: chmod +x gradlew
    - name: Check format, clean and build
      run: ./gradlew spotlessCheck clean build
      
